### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by hasshi1255** [hasshi1255/furima40757#23]
https://furima40757-1.onrender.com/#

**Comment by TakashiKozuma** [comment]
挙動確認依頼、ありがとうございます。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

- 購入画面を開いたところ、カード情報の入力欄が表示されませんでした。
本番環境でもクレジットカード情報が入力できるよう、修正をお願い致します。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hasshi1255** [comment]
訂正いたしました。
挙動確認済みです。
ご確認のほどよろしくお願いいたします。

**Comment by ushi10** [comment]
@hasshi1255 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**
**商品購入機能**
- [x] **クレジットカードの情報は購入の都度入力させること**
エラーハンドリングにより商品購入ページに戻された際、クレジットカード情報が入力できず購入できない状態です。
上記状態でも購入できるよう修正をしましょう。
<img width="332" alt="スクリーンショット 2024-09-20 10 20 22" src="https://github.com/user-attachments/assets/1bf8d3da-fa88-4bcc-8a5d-b9943ababb14">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by hasshi1255** [comment]
訂正いたしました。
挙動確認済みです。
ご確認のほどよろしくお願いいたします。
